### PR TITLE
libvirt: bump version to 6.3.0

### PR DESCRIPTION
**Pull request by insatomcat**
Take libvirt recipe from meta-virtualization (hardknott branch) to bump
its version to 6.3.0.
Libvirt 6.3.0 is required to do solve bug causing issue #22 (virsh
migrate returning 1 instead of 0 even though there was no problem)

Signed-off-by: insatomcat <florent.carli@rte-france.com>

### CODE REVIEW

**Review by watare — APPROVED** [review]

**Review by dupremathieu — COMMENTED** [review]
LGFM, I have launch test to check if there is no regression.

**Comment by ebail** [comment]
Hi Thanks for your work.

I would rework the commit message. It might sound picky but I believe it is important for the history of the project.

As described in https://github.com/seapath/.github/blob/main/CONTRIBUTING.md#styleguides,
please "Use the imperative mood in the subject line". Please explain what your are doing, it looks like you are taking libvirt from somewhere else, right ? Is it from meta-virtulization. Please explain it.

I would commit:

libvirt: bump version

Take libvirt recipe from meta-XXX to bump its version to 6.3.0.
Libvirt 6.3.0 is required to do X, Y and Z.

Thanks

**Review by ebail — CHANGES_REQUESTED** [review]
Hi Thanks for your work.

I would rework the commit message. It might sound picky but I believe it is important for the history of the project.

As described in https://github.com/seapath/.github/blob/main/CONTRIBUTING.md#styleguides,
please "Use the imperative mood in the subject line". Please explain what your are doing, it looks like you are taking libvirt from somewhere else, right ? Is it from meta-virtulization. Please explain it.

I would commit:

libvirt: bump version

Take libvirt recipe from meta-XXX to bump its version to 6.3.0.
Libvirt 6.3.0 is required to do X, Y and Z.

Thanks

**Review by ebail — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
